### ISSUE TITLE
Set up info for connecting client with server

### ISSUE THREAD

**Issue by marcelklehr** [magpie-ea/magpie-backend#105]
In magpie-base@0.3.0 the config [has changed](https://github.com/magpie-ea/magpie-base/blob/master/lib/templates/src/magpie.config.js#L2-L3) to only requiring the base URL of the backend server. It would be nice to adapt the backend to display that information when creating the experiment.

Problem is that some people probably still use the old version of magpie, so we'd have to include both versions.

**Comment by x-ji** [comment]
Sorry. Seem to have overlooked this one. Do you mean the URLs displayed in the "Edit Experiment" page? Though if only the base URL is required, I would assume it wouldn't need to be displayed for each individual experiment. I guess it wouldn't hurt to leave the API endpoint's URL on that page anyways, since it's a true statement about the backend endpoint in general, it's just that our Vue frontend knows how to call this endpoint without the end user's manual specification.

**Comment by x-ji** [comment]
Or maybe I could add "(to be provided in old _magpie frontend)" to that line, so that it becomes "Submission (to be provided in old _magpie frontend): [URL]". WDYT.

**Comment by marcelklehr** [comment]
Yeah that makes sense. Thanks
