### ISSUE TITLE
Add optional password prompt for deleting experiments

### ISSUE THREAD

**Issue by JannisBush** [magpie-ea/magpie-backend#40]
For the unprotected demo server and servers used in courses, it may be useful to protect the delete option of experiments with an extra password. At the moment, everybody could delete our example experiments and you could delete the experiments of your classmates. 

Either you could set a master password and only the server administrator could delete experiments, or the user could set a password while creating an experiment. 

This may not be urgent or necessary, but could be a nice protection against trolls.

**Comment by x-ji** [comment]
Initially I envisioned a system where there can be multiple users/accounts under one instance and each experiment would be linked to one account. However that can add some complications and our assumption was that everybody using the same instance should be in the same research group etc.

This sounds like a reasonable compromise. Maybe an optional password for each experiment which would be required when any operation is to be done? (e.g. results retrieval, modification, etc.)

@michael-franke What's your idea on this. Would an optional password per experiment suffice or would it be better to create an account system.

Also, I think because this repo was transferred into babe-project, not everybody is subscribed. You may want to subscribe to new issues and discussions by watching the repo in Github (besides the "Star" option).

**Comment by michael-franke** [comment]
How much extra effort would an account system be? — I do not think that it is strictly necessary, but it would be a good thing to have, it would help keep the number of instances (for course work etc.) lower.

**Comment by x-ji** [comment]
If we stick to username + password without requiring an email it can be manageable, though it would still require an overhaul of the current interface, e.g. only the experiments created by the current user would be shown, and the "download all experiments" option would only download all experiments created by this account.

One problem though is what happens when the user forgets their password. If we don't have a password reset mechanism then we'd need an admin or eventually the person who deployed the instance to save the day.

Maybe this can be a low-priority feature. Will the next course using this system be run only in the next semester?

**Comment by x-ji** [comment]
I'm taking a look at this again but this is tricky.

- If we want to implement a full-blown account system, it will be a lot of work. And it will not really be complete if we can't send emails to the users.

- If we allow everybody to set a password to an experiment, what could happen is that somebody could set passwords to all experiments that were already created, locking the original author out.

I will try to implement a solution where a password can only be set when the experiment was first created, after which it cannot be changed again. i.e. you either go with a fixed password at creation time, or you don't use any password at all.

**Comment by x-ji** [comment]
Decided to be not necessary at the moment.
