### ISSUE TITLE
Update local server

### ISSUE THREAD

**Issue by JannisBush** [magpie-ea/magpie-backend#43]
I was able to upgrade my test instance on heroku, but I am not sure how to update my local docker instance without recreating it? Is there a way to do it? If yes, this should be added to the documentation. Also, the documentation for upgrading the heroku instance is only in this README and not on the website, maybe it should be added there.

**Comment by x-ji** [comment]
Does it work if you only create the app-volume and not the db-volume? I think the DB should persist while the app itself can be recreated each time, which is normally how Docker deployments work. Though indeed I haven't tested the Docker version a lot recently.

Anyways I am looking to a Dockerless alternative as mentioned in #37, since it's mentioned that Docker might still be too scary to non-technical people.

**Comment by JannisBush** [comment]
I removed the container, the image and the volume and then tried to recreate the application, but I apparently forgot to remove something. After the recreation of the volumes and the container, I ran the app and it was still the same old version and the database was also still there. So, I am still not sure how to update it. 

If there is an easier way of deployment, I might be a good idea to move away from docker.
