### ISSUE TITLE
Shall we allow editing the <variants, chains, realizations> tuple after a complex experiment is created?

### ISSUE THREAD

**Issue by x-ji** [magpie-ea/magpie-backend#50]
Currently it is not allowed to do so since it would involve a lot of operations on the ExperimentStatus table with quite some considerations.

**Comment by JannisBush** [comment]
I see that it would be difficult to edit the variants and chains of an experiment after there are some submissions.
But we could allow the user to edit the triplet before there are any submissions, so if you make a typo at creating the experiment, you can edit it and don't have to delete and recreate the whole experiment. 
Also, we could allow the user the change the number of realizations, because this is almost equivalent to changing the number of maximum submissions and should not involve many or complex operations on the ExperimentStatus table.

**Comment by x-ji** [comment]
No need at the moment.
