### ISSUE TITLE
How to handle users quitting in an interactive experiment

### ISSUE THREAD

**Issue by JannisBush** [magpie-ea/magpie-backend#57]
#47  https://github.com/babe-project/color-reference/issues/1

On the front-end it would be nice to exit the normal view sequence and jump to an special end/apologize view. 

On the back-end this could correspond to the saving intermediate results issue.
In the [iterated-interactive-experiment](https://github.com/babe-project/iterated-interactive-example) there can arise some special problems. 
If one of the two users quits during the experiment, the other user will be notified and the experiment statuses get reset as expected.
Now, we add a postTest-view. The two participants finish the dialogue and the first participant fills out the questionnaire and sends the result to the server and closes his tab. The quit-handler is not active anymore, therefore participant 2 can still fill out the questionnaire. If participant 2 now quits the experiment without filling out the questionnaire, the statuses on the server of <1-X-X> will be 2 (finished) and of <2-X-X> will be 0 (not started yet). This effectively breaks the chain in my current front-end implementation. 
Here are several possible solutions.
1. Wait for both (all) participants to submit the questionnaire before sending/saving the results. (If one user now quits the questionnaire, both statuses will be reset)
    - If we do this on the client side, user 1 can't close his tab (bad)
    - Doing this on the server side should be possible
2. Only check if at least one of both participants of realization X-1 has submitted the results to the server and get his results.
    - Works for this experiment, because the saved conversation is the same for both users.
    - Won't work for experiments, where the results of the different participants of one chain-realization differ.
3. Save intermediate results after the experiment finishes, but before the users fill out the questionnaire.
    - The server has to somehow integrate/overwrite the intermediate results after the client sends the full results including the postTest questionnaire.
    - Brings up the question of are we allowed to use the results of participants who did not fill out the questionnaire? E.g. they could be underage or deliberately quit the experiment because they did not want their results to be saved.

**Comment by x-ji** [comment]
Nice catch. I think @michael-franke will have more input on this as this is related to experiment flow. AFAIK the post-experiment questionnaire is usually optional, so it might be best to save the results if the main part is already finished. But let's see then.

**Comment by x-ji** [comment]
I already wrote some code for saving intermediate results and it is feasible to overwrite the intermediate results with final results. If we go that route we can always save intermediate results once the main part is over, and the final overwriting would then be optional. Still, some more refactoring and testing would be needed to ensure it works. There might also be the issue of the frontend data lacking some fields which only exist in the final questionnaire, even though they might normally be empty.

**Comment by x-ji** [comment]
@JannisBush @elisakreiss @michael-franke  I'm now trying to come up with a first-step solution. Could it be like this:

- As Jannis mentioned in solution 1., even if only one participant quits before the full submission, the experiment statuses of all variants of this `chain-realization` combination get reset, so that we can be sure that newcomers have a fresh start.

- Since you also mentioned that we might still want to inspect the intermediate, incomplete results, the backend will provide the functionality to save intermediate experiment result at each step of the experiment (the client has to send a `"save_intermediate_results"` message). Each new intermediate result will overwrite the previous one. The final result will overwrite the intermediate result. There will be an additional field on `ExperimentResult` model, which identifies whether the result is an intermediate one or a final one.

The code for `save_intermediate_results` is actually already there when I first wrote the implementation. We just needed to clarify how we want to use it. Seems that the use case finally came now that we're running such experiments.

Please share your ideas regarding the proposed solution. If it looks good I'll start implementing it. If there's something to change/add further, please let me know.

**Comment by x-ji** [comment]
I implemented what @JannisBush suggested in the previous email:

- Whenever a result is submitted, all variants within the same `chain-realization` get their statuses set to `2` (finished)
- Whenever somebody quits halfway through, the other participants will submit their intermediate results to the server (I created another ticket in magpie-modules: https://github.com/magpie-ea/magpie-modules/issues/71 to also submit the data from the quitting participant as well)

I also made some minor updates to magpie-color-reference so that the submission of intermediate results work.

Please give it a try at https://magpie-backend.gigalixirapp.com/experiments/1/edit
