### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by polina-tsvilodub** [magpie-ea/magpie-backend#79]
I am trying to use the app for a magpie experiment hosted on a university server. (The experiments I host on netlify always work). When running it on MturkSandbox, the data seems to be submitted (number of submissions increases), however, I cannot retrieve the csv - the error message "internal server error" pops up. Are there particular settings to be added? Thanks!

**Comment by x-ji** [comment]
Hi Polina, thanks for the report. Could you point me to the exact experiment that was having problems? Thanks.

**Comment by x-ji** [comment]
And also the frontend experiment code, if availabble.

**Comment by polina-tsvilodub** [comment]
Hi Xiang,

The link to the experiment is
https://pragmatics-ptb.herokuapp.com/experiments/22
<https://pragmatics-ptb.herokuapp.com/experiments/22/edit> . However, now I
can access the csv, the issue no longer persists. Thanks!

Am Mo., 4. Nov. 2019 um 22:13 Uhr schrieb Xiang Ji <notifications@github.com

**Comment by x-ji** [comment]
👌  Sometimes there could be an error when the experiment response is a JSON array/object instead of a simple value. The newest version of the backend should have already fixed that. In some other cases, the backend simply times out if one tries to get all results at the same time. One might want to try again in that case. Glad that the issue is no longer there.
